name: ci

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   name: Install dependencies
                run: sudo apt-get update && sudo apt-get install -y git gcc g++ make cmake autoconf automake libtool gtk+-3.0 at-spi2-core webkit2gtk-4.0 curl python3 python3-pip
            -   name: Cache choosenim
                id: cache-choosenim
                uses: actions/cache@v1
                with:
                    path: ~/.choosenim
                    key: ${{ runner.os }}-choosenim-stable
            -   name: Cache nimble
                id: cache-nimble
                uses: actions/cache@v1
                with:
                    path: ~/.nimble
                    key: ${{ runner.os }}-nimble-stable
            -   uses: jiro4989/setup-nim-action@v1.0.2
                with:
                    nim-version: '1.2.0'
            -   name: Install dependencies
                run: nimble install --depsOnly -Y
            -   name: Run tests
                run: nimble ci
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   name: Install dependencies
                run: sudo apt-get update && sudo apt-get install -y git gcc g++ make cmake autoconf automake libtool gtk+-3.0 at-spi2-core webkit2gtk-4.0 curl python3 python3-pip
            -   name: Cache choosenim
                id: cache-choosenim
                uses: actions/cache@v1
                with:
                    path: ~/.choosenim
                    key: ${{ runner.os }}-choosenim-stable
            -   name: Cache nimble
                id: cache-nimble
                uses: actions/cache@v1
                with:
                    path: ~/.nimble
                    key: ${{ runner.os }}-nimble-stable
            -   uses: jiro4989/setup-nim-action@v1.0.2
                with:
                    nim-version: '1.2.0'
            -   name: Build Meros
                run: nimble build -Y
            -   uses: actions/upload-artifact@v1
                with:
                    name: meros-linux
                    path: build/Meros
